### ISSUE TITLE
Add helpers to add/remove attachments on records 

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-http.js#104]
* Leverage the decorator to check the capability

Proposal

New record:

```js
    client.bucket("blog").collection("posts")
      .addAttachment(dataURI)
```

New record with attributes:

```js
    client.bucket("blog").collection("posts")
      .addAttachment(dataURI, {id: "48408f90-5c9f-4088-9994-c04b7207ca58", type: "font"},
                              {permissions: {write: ["system.Everyone"]}})
```

Existing record:

```js
    client.bucket("blog").collection("posts")
      .addAttachment(dataURI, "48408f90-5c9f-4088-9994-c04b7207ca58",
                              {patch: true, safe: true, last_modified: 42})
```

Binary string

```js
    client.bucket("blog").collection("posts")
      .addAttachment(binaryString)
```

Delete attachment

```js
    client.bucket("blog").collection("posts")
      .deleteAttachment("48408f90-5c9f-4088-9994-c04b7207ca58")
```

**Comment by n1k0** [comment]
Alternative proposal:

New record:

```js
    client.bucket("blog").collection("posts")
      .createRecord({}, {attachment: dataURI})
```

New record with a permissions attribute:

```js
    client.bucket("blog").collection("posts")
      .createRecord({id: "48408f90-5c9f-4088-9994-c04b7207ca58", type: "font"},
                    {attachment: dataURI, permissions: {write: ["system.Everyone"]}})
```

Existing record:

```js
    client.bucket("blog").collection("posts")
      .updateRecord({id: "48408f90-5c9f-4088-9994-c04b7207ca58"},
                    {attachment: dataURI, patch: true, safe: true, last_modified: 42})
```

Binary string

```js
    client.bucket("blog").collection("posts")
      .createRecord({}, {attachment: binaryString})
```

Delete attachment

```js
    client.bucket("blog").collection("posts")
      .deleteAttachment("48408f90-5c9f-4088-9994-c04b7207ca58")
```

(For deletion we introduce a dedicated method because this is super specific)

Thoughts=? @leplatrem

**Comment by leplatrem** [comment]
The classic one between additional options and explicit methods :)

I guess that if you've come to this proposal, it's because it makes more sense where you'd use it, so I won't disagree!

If I step back and look for feedback, I see one or two disadvantages:
* the fact that the capability decorator will have to be put on every method (they will now require to issue a `GET /` to fetch server info)
* it blends a server plugin into the standard client methods
* in terms of documentation, a part will have to be documented as option, and the deletion in a dedicated section

**Comment by n1k0** [comment]
We should pair on this :)
