### ISSUE TITLE
Reflect name change in documentation

### ISSUE THREAD

**Issue by DirtyF** [Kinto/kinto-http.js#108]
Following #102 

All occurrences of kinto-client might be replaced with kinto-http in the docs:
https://doc.esdoc.org/github.com/Kinto/kinto-client/

**Comment by leplatrem** [comment]
The new URL is https://doc.esdoc.org/github.com/Kinto/kinto-http.js/

Please re-open if there are some leftovers!

**Comment by enguerran** [comment]
We need an admin to change the repository description in the top of [kinto-http's github homepage](https://github.com/Kinto/kinto-http.js). 

> A JavaScript HTTP client for the Kinto API. https://doc.esdoc.org/github.com/Kinto/kinto-client/

must be changed to

> A JavaScript HTTP client for the Kinto API. https://doc.esdoc.org/github.com/Kinto/kinto-http/

**Comment by DirtyF** [comment]
@enguerran to https://doc.esdoc.org/github.com/Kinto/kinto-http.js/ you mean ;)

**Comment by leplatrem** [comment]
Done! Thanks!
