### ISSUE TITLE
Expose the endpoint function to client programs

### ISSUE THREAD

**Issue by elelay** [Kinto/kinto-http.js#127]
`endpoint()` is currently not available to client programs.
If they want to make raw queries to the kinto server, using kinto.js, they have no way to use  ̀endpoint()` in 

```
var api = collection.api.bucket(collection.bucket).collection(collection.name)
api.client.execute({
 path: endpoint("collection", this.bucket.name, this.name),
 method: "HEAD",
 raw: true,
 headers,
})
```

They also need to add authentication, but it's the subject of another issue.

**Comment by elelay** [comment]
The code in #133 is wrong, but the discussion might still be of interest.

**Comment by paullaffitte** [comment]
I can't seem to find an endpoint() function, instead I found the object ENDPOINTS in endpoint.ts, containing several functions that allows to build urls. Is this issue still up to date or did the code already changed?

**Comment by leplatrem** [comment]
This could leverage the `endpoint` object, for example:
``` 
const url = client.endpoints.records(...);
```

**Comment by paullaffitte** [comment]
My pull requests (#543) has been superseded by #742 and this one has been merged. I think it means that this issue can be closed.

**Comment by leplatrem** [comment]
Thanks! Let us know if what was done in #742 covers your use-cases!
