### ISSUE TITLE
createBucket() needs to be provided with bucket id

### ISSUE THREAD

**Issue by tiberiuichim** [Kinto/kinto-http.js#171]
According to the Kinto API, http://kinto.readthedocs.io/en/latest/api/1.x/buckets.html#creating-a-bucket

> Creates a new bucket. If id is not provided, it is automatically generated.

The problem is that kinto-http.js requires the bucket id parameter. It should not require it, the generated bucket id can be retrieved from the response.

**Comment by n1k0** [comment]
Yes indeed, we're gonna fix this. Thanks for the report.

**Comment by n1k0** [comment]
Released in [v4.2.0](https://github.com/Kinto/kinto-http.js/releases/tag/v4.2.0).
