### ISSUE TITLE
`fetchServerInfo` + headers + memoization

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto-http.js#181]
`fetchServerInfo` stores a member variable `serverInfo` which is the value of the first "server info" response it got. This saves having to rerequest server info. However, `fetchServerInfo` accepts a `headers` option. Does `headers` change the behavior of the server? If so, we shouldn't rely on memoization in this way. If not, we shouldn't accept a `headers` option.

**Comment by Natim** [comment]
The headers option for the `fetchServerInfo` is to be able to pass the `Authorization` headers in order to get the `user_id` and the `bucket_id`. 👍 for memoization :)

**Comment by glasserc** [comment]
From a cursory review of the `hello` view in Kinto, it seems like the `settings` and `capabilities` fields of the hello response are not affected by authentication at all. In fact, the only thing that is affected by authentication is the `user` field. As a result, I'd propose removing `headers` from `fetchServerInfo`, `fetchServerSettings`, and `fetchServerCapabilities`, while changing `fetchUser` to not memoize (or to memoize only according to the `Authorization` header).
