### ISSUE TITLE
Error when trying to use kinto-http with ES5 require.

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-http.js#210]
```
var KintoClient = require("kinto-http").default;
new KintoClient(url);
```

TypeError: KintoClient is not a constructor

**Comment by leplatrem** [comment]
what do you have in `require("kinto-http")`? and what do you have in `.default`?

**Comment by Natim** [comment]
`.default` is undefined while `required("kinto-http")` returns `function KintoClient`

I guess it should be 
`var KintoClient = require("kinto-http");`
