### ISSUE TITLE
Handle Retry-After on HTTP 503

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto-http.js#34]
See what's done in kinto.py https://github.com/Kinto/kinto.py/blob/master/kinto_client/session.py#L69-L81

**Comment by almet** [comment]
That would be a valuable addition for the heroku deploys as well: The requests are currently timing out because the worker is starting.

**Comment by leplatrem** [comment]
Several solutions after a quick conversation with @n1k0 :

## minimal

* emit a `retry-after` event with the header value in payload.
Pros: would work like backoff
Cons: let the developers handle it, and possibly misbehave with what the server expects from clients.

## intermediary

Mimic python code.
* Add option N retry
* Wait N seconds and retry (`setTimeout`), where N initially comes from headers and then fibonacci to increase delay
* Raise error when retry exhausted
Pros: simple and assist the developper
Cons: keeps an event loop open, and several calls could retry in parallel

## nice

Same as intermediary but stack pending requests to avoid several calls to generate requests to the server while the *retry-after* is not elapsed.
