### ISSUE TITLE
Same signature for all lists ?

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-http.js#46]
Currently, only the list of records can be sorted, filtered, paginated.

Since the bucket, collection, and group list share the same capabilities (it's implemented [using the same resource](http://kinto.readthedocs.org/en/latest/concepts.html#technical-architecture)), we could also apply the same behaviour to every list method :)

(not a priority though).

**Comment by n1k0** [comment]
Nice! Agreed it's not P1 for now, but definitely nice to have eventually.
