### ISSUE TITLE
Replace EventEmitter with minimal interface and make it optional

### ISSUE THREAD

**Issue by dstaley** [Kinto/kinto-http.js#679]
For the most part, `kinto-http` is designed to be run in the browser. The only exception to that rule is that it requires an `EventEmitter`, which is a Node thing. Although `events` is only 5KB, alternatives like [`mitt`](https://github.com/developit/mitt) are only a handful of bytes.

I'd like to remove the hard dependency on `EventEmitter` by writing a generic `Emitter` interface that can accommodate any event emitter (making sure the interface is satisfied by `EventEmitter` and other libraries like [`mitt`](https://github.com/developit/mitt)).

I'd further like to make the event emitter optional. If an emitter isn't provided, the client won't be able to report the `backoff` parameter. This would mean that `backoff` would always be `0`, which is effectively the same as the `ignoreBackoff` parameter in `kinto.js`, so I think the breakage would be minimal.

Finally, if we agree to do this for `kinto-http`, I'd like to do it for `kinto` as well. Over there it looks like there'd be no loss in functionality if a consumer opted not to provide an emitter.

@leplatrem @Natim how does this sound to you? 

```ts
interface Emitter {
  emit(type: string, event?: any): void;
  on(type: string, handler: (event?: any) => void): void;
  off(type: string, handler: (event?: any) => void): void;
}

```

**Comment by leplatrem** [comment]
That sounds reasonable to me!

I'm definitely in favor of removing Node dependencies.

Thanks for the detailed explanation and your dedication! :pray: :pray:
