### ISSUE TITLE
Delete on plural endpoints

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-http.js#95]
The server supports `DELETE` on plural endpoints (`/buckets`, `/collections`, `/records`).

It supports the same filtering options as `listRecords()`.

It can be useful to delete multiple entries with one request:
- `DELETE /buckets` : delete every buckets for which I have write permission
- `DELETE /buckets?in_id=test,prueba,essai` : delete buckets with specified ids
- `DELETE /buckets/blog/collections?since="42"`: delete every collections in bucket whose timestamp > 42 for which I have write permission
- `DELETE /buckets/blog/collections/articles/records`: delete every records...

**Comment by lavish205** [comment]
This is pretty interesting, I would love to work on this.

**Comment by paullaffitte** [comment]
I would like to work on this too, since @lavish205 asked for it two years ago, I guess he is not working on it, so it will not be a duplicate work.

**Comment by Natim** [comment]
Sure go for it.

**Comment by leplatrem** [comment]
Fixed in #534
